# Generated by Django 4.2.27 on 2026-01-27 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=500, unique=True)),
                ('subject', models.CharField(db_index=True, max_length=500)),
                ('object', models.CharField(blank=True, max_length=500)),
                ('claim_type', models.CharField(db_index=True, max_length=100)),
                ('statement', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('source_uri', models.CharField(blank=True, max_length=500)),
                ('how_known', models.CharField(blank=True, max_length=50)),
                ('date_observed', models.DateField(blank=True, null=True)),
                ('digest_multibase', models.CharField(blank=True, max_length=200)),
                ('amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('curator', models.CharField(blank=True, max_length=300)),
                ('issuer_id', models.CharField(blank=True, max_length=300)),
                ('issuer_id_type', models.CharField(blank=True, max_length=20)),
                ('proof', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=500, unique=True)),
                ('ticker', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('metric', 'Metric'), ('label', 'Label'), ('categorical_grade', 'Categorical Grade')], max_length=20)),
                ('is_fixed', models.BooleanField(default=False, help_text='User cannot adjust weight to zero')),
                ('is_disqualifying', models.BooleanField(default=False, help_text='F on this = F overall')),
                ('min_weight', models.IntegerField(default=0, help_text='Floor that user cannot go below')),
                ('card_display_template', models.CharField(blank=True, help_text='Template like "${amt}M ({year})" for card display', max_length=200)),
                ('card_icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('grade', models.CharField(max_length=5)),
                ('raw_value', models.FloatField()),
                ('reason', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('source_claim_uris', models.JSONField(default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('badge_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10)),
                ('source_claim_uri', models.CharField(blank=True, max_length=500)),
                ('priority', models.IntegerField(default=0, help_text='Higher = shown first')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.company')),
                ('value', models.ForeignKey(blank=True, help_text='The value this badge was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.value')),
            ],
            options={
                'ordering': ['-priority', 'label'],
            },
        ),
        migrations.CreateModel(
            name='UserValueWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_weights', to=settings.AUTH_USER_MODEL)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_weights', to='core.value')),
            ],
            options={
                'unique_together': {('user', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('config', models.JSONField(default=dict, help_text='Thresholds for metrics, label→grade maps for categorical')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='core.value')),
            ],
            options={
                'unique_together': {('value', 'version')},
            },
        ),
        migrations.CreateModel(
            name='CompanyValueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('grade', models.CharField(max_length=5)),
                ('claim_uris', models.JSONField(default=list, help_text='URIs of claims this score derived from')),
                ('validation_count', models.IntegerField(default=0)),
                ('dispute_count', models.IntegerField(default=0)),
                ('highlight_on_card', models.BooleanField(default=False)),
                ('highlight_priority', models.IntegerField(default=0, help_text='Higher = shown first')),
                ('display_text', models.CharField(blank=True, help_text='Pre-rendered, e.g., "Lobbying: $11.1M (2024)"', max_length=200)),
                ('display_icon', models.CharField(blank=True, max_length=50)),
                ('scoring_rule_version', models.IntegerField(default=1)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_snapshots', to='core.company')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.value')),
            ],
            options={
                'unique_together': {('company', 'value')},
            },
        ),
    ]
