# Generated by Django 6.0.1 on 2026-01-26 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=500, unique=True)),
                ('subject', models.CharField(db_index=True, max_length=500)),
                ('object', models.CharField(blank=True, max_length=500)),
                ('claim', models.CharField(max_length=100)),
                ('statement', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('source_uri', models.CharField(blank=True, max_length=500)),
                ('how_known', models.CharField(blank=True, max_length=50)),
                ('date_observed', models.DateField(blank=True, null=True)),
                ('digest_multibase', models.CharField(blank=True, max_length=200)),
                ('score', models.FloatField(blank=True, null=True)),
                ('aspect', models.CharField(blank=True, max_length=100)),
                ('amt', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('curator', models.CharField(blank=True, max_length=300)),
                ('issuer_id', models.CharField(blank=True, max_length=300)),
                ('issuer_id_type', models.CharField(blank=True, max_length=20)),
                ('proof', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=500, unique=True)),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('grade', models.CharField(max_length=5)),
                ('raw_value', models.FloatField()),
                ('reason', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('source_claim_uris', models.JSONField(default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.company')),
            ],
        ),
    ]
