# Generated by Django 4.2.28 on 2026-02-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_companybadge_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=20, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=300)),
                ('brands', models.CharField(blank=True, help_text='Comma-separated brand names from product data', max_length=500)),
                ('owner', models.CharField(blank=True, help_text='Owner/manufacturer field from product data', max_length=300)),
                ('categories', models.CharField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('provider', models.CharField(help_text='Which API provided this: open_food_facts, open_beauty_facts, etc.', max_length=50)),
                ('raw_response', models.JSONField(default=dict, help_text='Full API response for debugging')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='Brand name as it appears on products', max_length=200)),
                ('brand_name_normalized', models.CharField(db_index=True, help_text='Lowercased, stripped version for matching', max_length=200)),
                ('source', models.CharField(blank=True, help_text='Where this mapping came from: manual, wikipedia, open_food_facts', max_length=100)),
                ('confidence', models.FloatField(default=1.0, help_text='0-1, how confident we are in this mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_mappings', to='core.company')),
            ],
            options={
                'ordering': ['-confidence', 'brand_name'],
                'unique_together': {('brand_name_normalized', 'company')},
            },
        ),
    ]
