# Generated by Django 4.2.28 on 2026-02-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_barcodecache_brandmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='display_group',
            field=models.CharField(blank=True, default='', help_text='Group name for frontend collapse. Empty = show individually.', max_length=100),
        ),
        migrations.AddField(
            model_name='value',
            name='display_group_order',
            field=models.IntegerField(default=0, help_text='Sort order for groups and ungrouped values in UI'),
        ),
    ]
