# Generated by Django 4.2.28 on 2026-02-19 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_value_display_group_value_display_group_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name as on shelf', max_length=300)),
                ('brand_name', models.CharField(db_index=True, help_text='Brand name, e.g. Cheerios, Doritos, Tide', max_length=200)),
                ('category', models.CharField(db_index=True, help_text='Product category for swap suggestions, e.g. cereal, water, chicken', max_length=100)),
                ('typical_price', models.DecimalField(blank=True, decimal_places=2, help_text='Typical retail price in USD', max_digits=8, null=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=20)),
                ('source', models.CharField(blank=True, help_text='Where this product data came from', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.company')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
