# Generated by Django 4.2.28 on 2026-02-27 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_product_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnmatchedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        db_index=True,
                        help_text="Product name from receipt",
                        max_length=300,
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        db_index=True,
                        help_text="Brand name from Claude AI",
                        max_length=200,
                    ),
                ),
                (
                    "parent_company_guess",
                    models.CharField(
                        help_text="Claude's guess for parent company", max_length=200
                    ),
                ),
                (
                    "category_guess",
                    models.CharField(
                        blank=True,
                        help_text="Category guess from Claude (optional)",
                        max_length=100,
                    ),
                ),
                (
                    "seen_count",
                    models.IntegerField(
                        default=1, help_text="Number of times this product was scanned"
                    ),
                ),
                (
                    "typical_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Most common price seen",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "approved_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="If approved, the Product that was created from this",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_unmatched",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-seen_count", "-last_seen_at"],
                "unique_together": {("product_name", "brand_name")},
            },
        ),
    ]
