# Generated by Django 4.2.28 on 2026-03-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companyvote'),
        ('core', '0007_company_website'),
    ]

    operations = [
    ]
