# Generated by Django 4.2.28 on 2026-10-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_0003_companyvote_0007_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Product photo, e.g. from Open Food Facts', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, db_index=True, help_text='What the product is, for like-for-like swaps, e.g. potato chips, chicken breast', max_length=100, null=True),
        ),
    ]
