# Generated by Django 4.2.28 on 2026-10-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_type_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmapping',
            name='role',
            field=models.CharField(blank=True, help_text='What this company does for the brand, e.g. manufacturer, marketer, owner outside North America', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, help_text="Every record found for this product, kept whole and keyed by source, e.g. {'usda_fdc': {...}, 'open_food_facts': {...}}", null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Display name for the company', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(blank=True, help_text='Industry sector for filtering', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.CharField(blank=True, db_index=True, help_text='NYSE/NASDAQ ticker symbol', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='uri',
            field=models.CharField(help_text='Canonical URI used as claim subject, e.g. company website', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Company homepage URL', max_length=500, null=True),
        ),
    ]
